### ISSUE TITLE
<username.github.io> deploy issues

### ISSUE THREAD

**Issue by runlevelsix** [hexojs/hexo-deployer-git#10]
This plugin seems seems to use an 'anti-pattern' to deploy sites to Github as a very different repository than what I have in my working directory. I don't know if I have it misconfigured or what, but I end up with a completely different repository layout on Github when using hexo-deployer-git than what I started with on my machine -- and I don't like that. It's a pretty bad misuse of git, I think.

I had everything setup and working using `hexo server`, but when I deployed it, my `CNAME` file and `atom.xml` file were missing. I'm using `runlevelsix.github.io` as my repo name - which does not use a `gh-pages` branch - only the `master` branch.

In the `_config.yml` file, I expected I could set the `config.public_dir` to something like the current directory, but that failed to have the expected results - pretty much all of my source files were deleted (major problem)...

Is this a git deployer issue, a haxo issue, or a github pages issue?

**Comment by Xuanwo** [comment]
`hexo-deployer-git` is used to deploy your html files to github instead of your source.
In order to manarge your source, your need to create a new branch or repo and control version with git by yuourself.

**Comment by runlevelsix** [comment]
I understand where you're coming from (I think). However, because my whole source tree is *my site* - even more than the `public/` folder is my site - because it includes all of the tools and other source files I need to build my site (hexo, npm modules, etc), this hexo plugin (or maybe it's hexo?) undermines my ability to keep my source in one place (a single github repository), and pull down a clone if something bad happens. I cannot do this right now with hexo-deployer-git because it overwrites my remote repository when I point it to my username.github.io repository.

Perhaps the fix that is needed is in the documentation: Notify the user of hexo-deployer-git that the repository they deploy to **must not** be the same repository as the one their source code is in. This can, however, cause lots of problems for people who setup hexo in the repository intended to host the deployed site (username.github.io), for example.

**Comment by leesei** [comment]
You can specify the branch to push to in `branch` option.
I suppose that is basic knowledge one has to equip himself when using git/GitHub.
This repo does not intend to educate on those.

**Comment by tara1128** [comment]
I used "hexo init" in a subdirectory of my git, but after "hexo deploy", my index.html was overwrittten and the log of git had all lost, only 2 for hexo left.... I was mad!
