### ISSUE TITLE
FATAL: can't deploy with https url

### ISSUE THREAD

**Issue by LEAFERx** [hexojs/hexo-deployer-git#102]
recently github remove the tls1.0/1.1
now that this plugin can't work with the https url
when i run`hexo d`, error occurred as `fatal: HttpRequestException encountered.`
ssh url is still working

i guess the problem is at https://github.com/hexojs/hexo-deployer-git/blob/master/lib/deployer.js#L89
because when i run `git push -u <#myhttpsurl>` same error occurred. then bash prompt me to enter the username&password of github

**Comment by JLHwung** [comment]
Please update the [Git Credential Manager for Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v1.14.0), see https://github.com/hexojs/hexo/issues/3043#issuecomment-368009045

**Comment by LEAFERx** [comment]
Problem solved! THX!
