### ISSUE TITLE
local repository and remote repository inconsistent

### ISSUE THREAD

**Issue by Agenric** [hexojs/hexo-deployer-git#105]
Because git is not sensitive to the case of file names by default, If you put a file name changed from lowercase to uppercase or uppercase to lowercase, at this time, if you executed `hexo d`. You will your  find the file structure of the local repository and the remote repository are inconsistent. It may cause some pages to generate a 404 error.

**Comment by stevenjoezhang** [comment]
Run
```
git rm -rf --cached . && git add .
```
in the `.deploy_git` directory
