### ISSUE TITLE
vulnerability in hexo-deployer-git

### ISSUE THREAD

**Issue by Genuifx** [hexojs/hexo-deployer-git#117]
hey bro. There is 1 low severity vulnerability in 3307 scanned packages

![image](https://user-images.githubusercontent.com/10156994/49141440-8976a000-f331-11e8-8e25-5b271328261e.png)

**Comment by YoshinoriN** [comment]
@Genuifx 
Thanks a report.
Current master branch has already fixed this issue. Please wait a next release.

**Comment by YoshinoriN** [comment]
@Genuifx 
We released v1.0.0

> https://github.com/hexojs/hexo-deployer-git/releases/tag/1.0.0

Thanks :)
