### ISSUE TITLE
什么时候生成一份新的release包

### ISSUE THREAD

**Issue by Kerminate** [hexojs/hexo-deployer-git#119]
命令行安装之后提示依赖过期 是uglify-js这个包，使用这个依赖的是swig这个包。我看仓库里最新的代码已经把包换成 swig-templates，怎么不发布一版release包呢

**Comment by iljh** [comment]
I think you need read the README.md carefully.

>If you want to use the latest features of hexo-deployer-git, you may install it from github:
for npm version under 4
`$ npm install git+git@github.com:hexojs/hexo-deployer-git.git --save`
for npm version 5
`$ npm install git+ssh://git@github.com:hexojs/hexo-deployer-git.git --save`

**Comment by benc-uk** [comment]
Does not work
Can you create a release on NPM with the latest?

```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/hexojs/hexo-deployer-git.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128
```

**Comment by YoshinoriN** [comment]
@benc-uk 
That errors maybe ssh key's permission error. It will not fix even if release latest package.
Would you please check your ssh key permission or use https protocol.

**Comment by JLHwung** [comment]
Closed via https://github.com/hexojs/hexo-deployer-git/releases/tag/1.0.0.

@benc-uk your issue is not related to the release cycle, please open a new issue, thanks.
