### ISSUE TITLE
Can it pull existing repo into deployDir instead of initializing new ?

### ISSUE THREAD

**Issue by iJackUA** [hexojs/hexo-deployer-git#12]
According to this code https://github.com/hexojs/hexo-deployer-git/blob/master/lib%2Fdeployer.js#L54
plugin try to fins exisiting deployDir and if not - create and Init new repo, then creates a "First commit".

When I make deployments from my dev machine - it is fine (repo is created once and then commits are added), but when I use "CircleCI" CI/CD service - it makes each build in clean Docker container, so deloyDir is always absent. That's why "gh-pages" branch always cleared and rewritten with 2 commits - "First commit" and "Repo is updated...".

I thought that is could be a way - to try to checkout exisiting repo/branch first and only if there is nothing - try to init new. What do you think ?

P.S. That's not a critical thing, but would look nicer and not confusing.

**Comment by Xuanwo** [comment]
Yes, you can read my `.travis.yml` : https://github.com/Xuanwo/xuanwo.github.io/blob/blog/.travis.yml
