### ISSUE TITLE
发布到github上报错

### ISSUE THREAD

**Issue by MarcoPai** [hexojs/hexo-deployer-git#13]
我的配置：
    # Deployment
    ## Docs: http://hexo.io/docs/deployment.html
    deploy:
      type: git
      repo: https://github.com/MarcoPai/MarcoPai.github.io.git
      branch: master

输入 hexo d 之后的报错：

INFO  Copying files from public folder...
    events.js:85
          throw er; // Unhandled 'error' event
                    ^
Error: spawn git ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

**Comment by MarcoPai** [comment]
我本地没有安装git，而是直接安装的 github for windows

**Comment by cxumol** [comment]
别用2.0以上的git。用回1.9.5吧

**Comment by leesei** [comment]
你在cmd 打git 能喚出git 嗎?

**Comment by Xuanwo** [comment]
@MarcoPai github for windows 的话，需要在`git bash`中执行`hexo d`命令
