### ISSUE TITLE
no git tag for 2.0.0

### ISSUE THREAD

**Issue by noraj** [hexojs/hexo-deployer-git#150]
2.0.0 was released on npmjs 2 month ago

![image](https://user-images.githubusercontent.com/16578570/68064684-08810f00-fd1f-11e9-8bb7-3fe88ad83a1b.png)

But has never been released on github https://github.com/hexojs/hexo-deployer-git/releases

![image](https://user-images.githubusercontent.com/16578570/68064691-1898ee80-fd1f-11e9-8ef4-8fea71bc383b.png)

It in the master branch but there is no 2.0 tag 

![image](https://user-images.githubusercontent.com/16578570/68064702-2d758200-fd1f-11e9-8974-670bc6b8b8df.png)

**Comment by YoshinoriN** [comment]
@noraj 
Thank you for your report :)
We added 2.0.0 release tag.

> https://github.com/hexojs/hexo-deployer-git/releases/tag/2.0.0

@curbengh 
Thank you :)
