### ISSUE TITLE
能否支持https那种输入密码的git仓库？

### ISSUE THREAD

**Issue by luodaoyi** [hexojs/hexo-deployer-git#16]
大陆有很多免费的应用引擎可以用 
 但是都只是支持https形式的 
能否增加https账号密码的参数 使用travis-ci.org 加密参数以后可以自动部署？

**Comment by Xuanwo** [comment]
不能配置密钥么？
要是提供了这样的参数- -，然后一坨小白直接明文了怎么破。。
相信我，肯定会有的。。

**Comment by Xuanwo** [comment]
如果确实有这样的需求，你可以考虑git的支持： https://git-scm.com/book/zh/v2/Git-%E5%B7%A5%E5%85%B7-%E5%87%AD%E8%AF%81%E5%AD%98%E5%82%A8

**Comment by luodaoyi** [comment]
@Xuanwo 新浪ACE还有百度BAE 都是只能密码上传  妹的

**Comment by Xuanwo** [comment]
@luodaoyi 可以少跑一个`ssh-agent`呀，233

**Comment by luodaoyi** [comment]
@Xuanwo 哈哈这个方法可以 可以在自动部署的时候用
```
echo "xxx" > ~/.key
```
然后使用全局变量加密"xxx"搞定
