### ISSUE TITLE
Unable to automatically detect email address

### ISSUE THREAD

**Issue by ghoolooloo** [hexojs/hexo-deployer-git#161]
My email is of the form "xxx.xxx@xxx.xxx", but when I deploy, it always prompts me "fatal: Unable to automatically detect email address". Is this mode of email not supported?

**Comment by SukkaW** [comment]
@ghoolooloo More details are required. For example, the full error log and how does your configuration look like. Otherwise I have no choice but close this issue with a label `invalid`.

**Comment by stevenjoezhang** [comment]
There is a discussion about it: https://stackoverflow.com/questions/25671785/git-fatal-unable-to-auto-detect-email-address
I'm closing this issue. Please join the discussion there :)
