### ISSUE TITLE
为何我执行hexo d后没有任何反应

### ISSUE THREAD

**Issue by sunxfancy** [hexojs/hexo-deployer-git#17]
表示看不到任何提示，没法确定问题

**Comment by leesei** [comment]
你用`hexo g` 有反應嗎? 會否生成 `public/`?
npm install 合適的modules 了?

**Comment by sunxfancy** [comment]
好吧,我昨晚已经解决了,发现是配置文件有两行配置了同样的内容,十分建议增加配置文件解析部分的异常错误,要不太难定位问题了
