### ISSUE TITLE
Can it "git pull" from the repo before deploy instead of just "git push --force"?

### ISSUE THREAD

**Issue by CHN-ChenYi** [hexojs/hexo-deployer-git#172]
I've lost all my commit history right now (┬_┬)

**Comment by SukkaW** [comment]
So you mean an `keep_history` option?

**Comment by CHN-ChenYi** [comment]
> So you mean a `keep_history` option?

Exactly. Thanks!

**Comment by stevenjoezhang** [comment]
There is a discussion about it: #33
I'm closing this issue. Please join the discussion there :)
