### ISSUE TITLE
deploy自动将.deploy_git文件夹中的.html文件忽略

### ISSUE THREAD

**Issue by Wchoward** [hexojs/hexo-deployer-git#194]
使用`hexo d`将静态页面push到github master分支时，会自动忽略`.deploy_git`中所有的html文件，不会对.html文件create mode

<img width="778" alt="image" src="https://user-images.githubusercontent.com/29882211/95669774-c0b56980-0bb6-11eb-9712-26d83c298640.png">

**Comment by stevenjoezhang** [comment]
能否检查一下你的机器上的全局`gitignore`设置？例如其它 git 仓库中的`.html`文件是否有类似问题？

**Comment by Wchoward** [comment]
> 能否检查一下你的机器上的全局`gitignore`设置？例如其它 git 仓库中的`.html`文件是否有类似问题？

啊 检查了一下，确实是用户根目录的全局`gitignore`里把`.html`文件加进去了。谢谢！
