### ISSUE TITLE
关于github开启Two factor authentication之后无法使用用户名密码提交

### ISSUE THREAD

**Issue by jqdelove** [hexojs/hexo-deployer-git#196]
github将于2021年8月13日停止使用用户名和密码进行提交代码，我今天在开启Two factor authentication之后确实发现了这个问题，不能够再通过用户名和密码提交代码，想提问一下这个问题如何解决呢[截图](http://106.14.236.195:8090/images/ross/test.png)

**Comment by SukkaW** [comment]
使用 Personal Access Token 代替密码提交即可。

**Comment by jqdelove** [comment]
非常感谢！已经成功
