### ISSUE TITLE
default commit msg 'site update: xxxx-xx-xx xx:xx:xx' timezone issue

### ISSUE THREAD

**Issue by sabrinaluo** [hexojs/hexo-deployer-git#21]
Date is now the local machine time.
If travis is used, time will be the timezone of travis.
Can we use the config.timezone to set the date for commit msg, if the timezone is set in _config.yml?

**Comment by h404bi** [comment]
I think nope, but you can use `TZ` variable to correct timezone while using travis. [Example](https://github.com/h404bi/notes/blob/master/.travis.yml#L12)

**Comment by sabrinaluo** [comment]
Ah, thanks, this solves the problem. :+1:

**Comment by Xuanwo** [comment]
Closed for wontfix.
