### ISSUE TITLE
Does not support Github Pages custom domains

### ISSUE THREAD

**Issue by yowmamasita** [hexojs/hexo-deployer-git#22]
It will always overwrite the placed CNAME file on the repo

**Comment by leesei** [comment]
I think the solution should be putting CNAME in `source`, so it is available in the generated folder.

**Comment by yowmamasita** [comment]
@leesei oh right, my implementation had too many holes in it. Thanks!

**Comment by leesei** [comment]
You are welcome to put the method to FAQ if you have worked it out. :+1:

**Comment by immysl** [comment]
I tried putting the CNAME in `source` but unfortunately it does not appear in the repo when deployed.

**Comment by leesei** [comment]
@immysl I tested and it's in `public/`. Deployers are supposed to deploy that folder, please double check.

**Comment by immysl** [comment]
@leesei I got it wrong, my bad. I forgot to generate the static files while deploying. Anyway thanks for the tip on the `source` folder.

**Comment by leesei** [comment]
Great, happy blogging with Hexo.
