### ISSUE TITLE
I added a CNAME file under the root directory however it won't push to the remote repo

### ISSUE THREAD

**Issue by xxf1995** [hexojs/hexo-deployer-git#26]
I added a CNAME file under the root directory however it won't push to the remote repo; so I manually add a CNAME file at the remote repo. However, every time I run "hexo d -g"; the CNAME file will disappear.

**Comment by leesei** [comment]
Does the CNAME file exist in `.deploy_git/` folder?

**Comment by leesei** [comment]
hexo.io is using a CNAME file in `source/`
https://github.com/hexojs/site/tree/master/source

**Comment by leesei** [comment]
Put CNAME in `source/`, I tested and it's in `public/` after `hexo generate`. Deployers are supposed to deploy content of that folder, please double check.

**Comment by bwangel23** [comment]
@leesei ，thanks，you answer has soloved my question!
