### ISSUE TITLE
ERROR Deployer not found: git

### ISSUE THREAD

**Issue by LukeLiou** [hexojs/hexo-deployer-git#270]
I met this problem after I execute `npm install hexo-deployer-openshift --save`, hope ur reply soon, thx

**Comment by yoshinorin** [comment]
@LukeLiou 

Please see https://github.com/hexojs/hexo-deployer-git/issues/90
BTW, `hexo-deployer-openshift` is deprecated. Please use other deployer.

**Comment by LukeLiou** [comment]
Could you plz recommend any other deployer?

**Comment by LukeLiou** [comment]
> @LukeLiou
> 
> Please see #90 BTW, `hexo-deployer-openshift` is deprecated. Please use other deployer.

Could you plz recommend any other deployer?

**Comment by yoshinorin** [comment]
I don't know. Its a case-by-case. If you want to deploy to GitHub pages you can use hexo-deployer-git, GitHub Actions etcetc...

**Comment by LukeLiou** [comment]
> I don't know. Its a case-by-case. If you want to deploy to GitHub pages you can use hexo-deployer-git, GitHub Actions etcetc...

Use Github Actions

> I don't know. Its a case-by-case. If you want to deploy to GitHub pages you can use hexo-deployer-git, GitHub Actions etcetc...

Its still report error `ERROR Deployer not found: git` even though use github Actions, I wanna deploy my hexo post to github pages🙁
![image](https://user-images.githubusercontent.com/43230973/190944965-cecf6c1e-d452-48b0-92d0-8fc4a8392f29.png)

**Comment by LukeLiou** [comment]
![image](https://user-images.githubusercontent.com/43230973/190946800-13297e2a-f054-49bb-aff9-eb7a615047a6.png)
@yoshinorin This is a package.json screenshot , hope ur reply soon, thx.

**Comment by LukeLiou** [comment]
@yoshinorin I reconfigure the plugin in _config.yml, resolved👍
