### ISSUE TITLE
ERROR Deployer not found: git

### ISSUE THREAD

**Issue by edagarli** [hexojs/hexo-deployer-git#28]
hexo-site@0.0.1 /Users/jhp-android/Desktop/github/edagarli.github.io
├─┬ hexo-admin@1.1.2
│ └─┬ hexo-util@0.1.7 
│   ├── bluebird@2.10.2 
│   └── highlight.js@8.9.1 
└─┬ hexo-deployer-git@0.0.4 
  ├─┬ chalk@0.5.1 
  │ ├── ansi-styles@1.1.0 
  │ ├─┬ has-ansi@0.1.0 
  │ │ └── ansi-regex@0.2.1 
  │ ├── strip-ansi@0.3.0 
  │ └── supports-color@0.2.0 
  └─┬ hexo-util@0.1.7 
    ├── bluebird@2.10.2 
    └── highlight.js@8.9.1 

justhacker:edagarli.github.io justhacker$ hexo deploy
ERROR Deployer not found: git

**Comment by benloong** [comment]
i got this error too: 
ERROR Deployer not found: git

**Comment by edagarli** [comment]
check  config file , delete the plugins
