### ISSUE TITLE
Cannot deploy when src refspec is not master

### ISSUE THREAD

**Issue by h404bi** [hexojs/hexo-deployer-git#3]
In a `.deploy_git` repo, if the `src refspec` is NOT `master`, deploy would fail.
e.g. The `src refspec` is `pages` in https://travis-ci.org/h404bi/notes/builds/63832305
`498 error: src refspec master does not match any.`

The problem is that because in lib `deployer.js`, `src refspec` is specified to `master`:
https://github.com/hexojs/hexo-deployer-git/blob/master/lib/deployer.js#L71
``` js
 return git('push', '-u', repo.url, 'master:' + repo.branch, '--force');
```

Remove `'master:' + ` should solve the problem, maybe has other solutions.
``` js
 return git('push', '-u', repo.url, repo.branch, '--force');
```

**Comment by h404bi** [comment]
@Xuanwo It seems to work using `"HEAD:"` src refspec rather than just remove the `"master:"`.
And `HEAD` is pointing to `current branch`, so it can fix the problem.
ref: https://stackoverflow.com/questions/4181861/src-refspec-master-does-not-match-any-when-pushing-commits-in-git
``` sh
~/workspace/test/hexo-deployer-git (master) $ npm test

> hexo-deployer-git@0.0.4 test /home/ubuntu/workspace/test/hexo-deployer-git
> gulp test

[13:57:23] Using gulpfile ~/workspace/test/hexo-deployer-git/gulpfile.js
[13:57:23] Starting 'coverage'...
[13:57:24] Starting 'jshint'...
[13:57:24] Finished 'coverage' after 1.65 s
[13:57:24] Starting 'mocha'...
[13:57:25] Finished 'jshint' after 1.27 s


  Git deployer
    deployer
      ✓ default (305ms)
      ✓ custom branch (158ms)
      - custom message
On branch master
nothing to commit, working directory clean
To /home/ubuntu/workspace/test/hexo-deployer-git/test/deployer_test/remote
 * [new branch]      HEAD -> master
Branch master set up to track remote branch master from /home/ubuntu/workspace/test/hexo-deployer-git/test/deployer_test/remote.
On branch master
nothing to commit, working directory clean
Everything up-to-date
Branch master set up to track remote branch master from /home/ubuntu/workspace/test/hexo-deployer-git/test/deployer_test/remote.
      ✓ multi deployment (209ms)
    parse config
      ✓ single repo, no branch
      ✓ single repo, with branch
      ✓ single repo, branch after url
      ✓ multiple repo
      ✓ github repo, master branch
      ✓ github repo, gh-pages branch
      ✓ github repo, custom branch
      ✓ gitcafe repo, gitcafe-pages branch
      ✓ gitcafe repo, custom branch
      ✓ repo is required


  13 passing (1s)
  1 pending

----------------------|-----------|-----------|-----------|-----------|
File                  |   % Stmts |% Branches |   % Funcs |   % Lines |
----------------------|-----------|-----------|-----------|-----------|
   lib/               |     87.21 |     93.33 |       100 |      86.9 |
      deployer.js     |     81.03 |        80 |       100 |      80.7 |
      parse_config.js |       100 |       100 |       100 |       100 |
----------------------|-----------|-----------|-----------|-----------|
All files             |     87.21 |     93.33 |       100 |      86.9 |
----------------------|-----------|-----------|-----------|-----------|


=============================== Coverage summary ===============================
Statements   : 87.21% ( 75/86 )
Branches     : 93.33% ( 28/30 )
Functions    : 100% ( 19/19 )
Lines        : 86.9% ( 73/84 )
================================================================================
[13:57:27] Finished 'mocha' after 2.16 s
[13:57:27] Starting 'test'...
[13:57:27] Finished 'test' after 12 μs
```

**Comment by Xuanwo** [comment]
so I don't think it should be changed.
as my test, it work will in the condition that branch is not master.

**Comment by h404bi** [comment]
Why？这个就是要解决当分支名不是master的情况啊。
原来代码指定了本地分支一定为`master:`，如果克隆下来当前分支是master的话push就没问题，像https://github.com/hexojs/hexojs.github.io。
```sh
$ git branch
* master
$ git push -u <repo.url> master:<repo.branch> --force    ok.
```

但如果克隆下来后当前分支是别的分支名呢，那么指定用`master:`来push就会失败了，因为本地分支不是master，指定用master肯定失败。
```sh
$ git branch
* pages
$ $ git push -u <repo.url> master:<repo.branch> --force    failed.
```

引用stackoverflow的解决方法：https://stackoverflow.com/a/4183856/3651279 
用`HEAD`，`HEAD`指向当前分支，当克隆下来本地分支是`master`的话，`HEAD`表示`refs/heads/master`，指定`master`；当克隆下来本地分支是其它分支名的话，`HEAD`表示`refs/heads/<branch>`，指向`<branch>`，这样能够解决当本地分支不是`master`的情况。比如本地分支是`pages`，`HEAD`表示`refs/heads/pages`，就指定`pages`了。

**Comment by Xuanwo** [comment]
我之前测试过一个使用gh-pages分支的，并没有问题啊= =

**Comment by Xuanwo** [comment]
我好像理解你的问题了，其实这个插件的工作原理并不是你理解的那样。

对于一个新的库，它的操作是：
```
  function setup(){
    // Create a placeholder for the first commit
    return fs.writeFile(pathFn.join(deployDir, 'placeholder'), '').then(function(){
      return git('init');
    }).then(function(){
      return git('add', '-A');
    }).then(function(){
      return git('commit', '-m', 'First commit');
    });
  }
```
也就是说，它会在本地初始化一个新的库，而不是clone你之前的库。
然后可以看到，在push的时候，使用的代码是：
```
return git('push', '-u', repo.url, 'master:' + repo.branch, '--force');
```
这里的`-u`参数是指：
```
-u
--set-upstream
For every branch that is up to date or successfully pushed, add upstream (tracking) reference, used by argument-less git-pull(1) and other commands. For more information, see branch.<name>.merge in git-config(1).
```
也就是说，用来指定上游。

所以，不管你最后远端使用的是什么分支，本地始终都是master分支，这个是不冲突的。

**Comment by h404bi** [comment]
No no no，我知道，初始化库的条件是在检测本地没有克隆之前的部署库后的，但如果在deploy之前有克隆部署库，那么就会不初始化新库而，使用克隆下来的部署库，然后拷贝public目录下的文件。你在仔细看看deployed.js的逻辑 :)

**Comment by Xuanwo** [comment]
重点在于- -，我们这个插件根本就不会去克隆库啊。。

你是想说，自己克隆了库，然后使用这个插件就会有问题是么。。

**Comment by Xuanwo** [comment]
额- -，我对JS不太了解。

不过观察下面的代码：
```
 return fs.exists(deployDir).then(function(exist){
    if (exist) return;

    log.info('Setting up Git deployment...');
    return setup();
  }).then(function(){
    log.info('Clearing .deploy folder...');
    return fs.emptyDir(deployDir);
  }).then(function(){
    log.info('Copying files from public folder...');
    return fs.copyDir(publicDir, deployDir);
  }).then(function(){
    return parseConfig(args);
  }).each(function(repo){
    return push(repo);
  });
};
```

要是存在的话，他会执行`return fs.emptyDir(deployDir);`。
这么说- -，按照之前的假设，确实会出现问题。。

**Comment by h404bi** [comment]
对，插件本身不会自己克隆库，但若要实现像https://github.com/hexojs/hexojs.github.io/commits/master 这样的持续性的commits就必须要在deploy之前加一句克隆库https://github.com/hexojs/site/blob/master/.travis.yml#L21 ，然而插件本身定死了本地分支为master，用在https://github.com/hexojs/hexojs.github.io 没问题，因为分支是master，但分支是其它名字就不行了。

你还是不懂我的问题，也是，不亲身遇到问题一时也是难以明白，或者我说的不清楚吧。

**Comment by Xuanwo** [comment]
我理解你的问题了。

不过用`HEAD:`的话，同样会存在一些问题，比如像我这样的奇葩会把`blog`分支设为主分支，然后`git clone`下来之后，`HEAD`并没有指向`master`。

**Comment by h404bi** [comment]
试试加`-b`参数
```sh
$ git clone https://github.com/Xuanwo/xuanwo.github.io.git
$ git branch
* blog

$ git clone -b master https://github.com/Xuanwo/xuanwo.github.io.git
$ git branch
* master
```

然后再进`.git`目录查看`HEAD`文件。

**Comment by Xuanwo** [comment]
刚才试了一下，我觉得使用`HEAD`是可行的，不过可能在Wiki中需要标明一下使用须知之类的。

**Comment by h404bi** [comment]
Finally you understood... :sob: 这问题我放这十几天了，我以为tommy会来修复，然而并没有.... 所以我就试着修一下。。

**Comment by Xuanwo** [comment]
咳咳- -，以前并没有这样的需求，所以无法理解。。。Sorry。。

我直接合并吧，毕竟这个改动不会影响按照流程操作的童鞋。

**Comment by sabrinaluo** [comment]
@h404bi @Xuanwo 
遇到了类似的问题。
我以前是在自己本地有一个`.deploy_git`的文件夹，这个是自己克隆的，而且是master分支
之后我修改了远程的repo，也就是把内容放到了远程的gh-pages分支
想要保留之前的提交记录，在travis deploy之前，从远程克隆了gh-pages分支放到`.deploy_git`文件夹，然后遇到了这个src refspec is not master的error。
请问是否有办法解决呢？谢谢

**Comment by Xuanwo** [comment]
```
git clone -b master git@github.com:Xuanwo/xuanwo.github.io.git .deploy_git
```

然后hexo d即可

可以参考： https://github.com/Xuanwo/xuanwo.github.io/blob/blog/.travis.yml

**Comment by sabrinaluo** [comment]
@Xuanwo 你好，我现在是这么写的：
`git clone git@github.com:sabrinaluo/tech.git -b gh-pages --single-branch .deploy_git`
因为我的内容在远程的gh-pages里
你提供的命令，必须要把内容放在master分支才可以。

**Comment by sabrinaluo** [comment]
已经解决啦，:smiley:
因为`npm install hexo-deploer-git`自动安装的是0.0.4版本，你的这个commit还没有新的release tag，用新版的就可以。
把`package.json`里改成
```
"hexo-deployer-git": "hexojs/hexo-deployer-git#495fc6d"
```
就可以了

**Comment by h404bi** [comment]
@sabrinaluo 请手动替换一下 `deployer.js`，因为当时我 pull request 修复这个问题后，这个插件到现在都还没有更新 release。e.g.: https://github.com/h404bi/notes/blob/master/.travis.yml#L42

**Comment by Xuanwo** [comment]
@tommy351 please update the version on npm
