### ISSUE TITLE
Hexo One-Command Deployment Does Not Support GitHub Fine-Grained Personal Access Tokens

### ISSUE THREAD

**Issue by leimao** [hexojs/hexo-deployer-git#309]
Hexo One-Command Deployment Does Not Support GitHub Fine-Grained Personal Access Tokens

**Comment by uiolee** [comment]
it works well

**Comment by leimao** [comment]
> in my case, it works well

Thanks a lot. I spent more time investigating this and found a solution. For folks who have not made it working, please check this blog post ["Hexo Deployment on GitHub Using GitHub Fine-Grained Tokens"](https://leimao.github.io/blog/Hexo-Deployment-GitHub-Fine-Grained-Tokens/).
