### ISSUE TITLE
Error:  The ayer theme could not be found.

### ISSUE THREAD

**Issue by xiaoxpai** [hexojs/hexo-deployer-git#313]
试过了好几个主题，jobs build都是报这个错

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/39144603/232518022-6fb158b6-cb3f-41d2-816d-befe0734a7aa.png">

**Comment by stevenjoezhang** [comment]
你好，这是 Hexo 平台，你用的 Jekyll 当然会报错。

**Comment by xiaoxpai** [comment]
你好，感谢回答，我在本地hexo -s可以运行，但是git push 到github Action构建就这样了，默认的主题好像就是Jekyll，提示找不到这个主题，我安装其他主题也是报这个错/(ㄒoㄒ)/~~

**Comment by stevenjoezhang** [comment]
你需要自定义 GitHub Actions，可以参考文档 https://hexo.io/zh-cn/docs/github-pages
