### ISSUE TITLE
After deploy, github page (with custom domain) goes down for a couple of minutes.  

### ISSUE THREAD

**Issue by patrickbolle** [hexojs/hexo-deployer-git#32]
Hey there, loving Hexo so far, thanks for all of the hard work put into it.
I've got my github pages set up perfectly with my domain (patrickbollenbach.me) . All is well for the most part.

Except when I deploy to my "patrickbolle.github.io" repo using the hexo deploy command -- 
My pages domain goes down for a couple minutes.
I've got a CNAME file directing to patrickbollenbach.me so patrickbolle.github.io will always redirect to that domain.

Anybody have this problem?
it's not a major deal, but if i'm making small mods/new posts/ etc my site will keep crashing even for small periods of time.

Thanks!

**Comment by gkatsev** [comment]
this deployer does a force-push to the repo and will overwrite everything. What I've found as a work-around is to add the CNAME file to the `source` folder of hexo so that when it's generated it gets put into the root of the gh-pages branch.
