### ISSUE TITLE
Commited history will be overwriten if I work with two computers

### ISSUE THREAD

**Issue by CodingJoker** [hexojs/hexo-deployer-git#36]
I want to write my hexo blog on two computers ,  however, when I used two computers to do this thing,  the commited history will be overwriten by each other.

**Comment by gkatsev** [comment]
This is definitely something that needs to change. I guess https://github.com/hexojs/hexo-deployer-git/issues/33 is related.

**Comment by gkatsev** [comment]
Now that I think about it, it definitely can be two separate issues. You can definitely continue force-pushing to the repo without losing all the history of it.

**Comment by gkatsev** [comment]
The solution would be for the setup function clone the repo/branch and then before pushing an update pulling down what's there.

**Comment by twang2218** [comment]
I ran into the same problem, which I'm using travis CI for the continuous deployment, which caused all the pages history lost every time there is an update.

@Xuanwo Could you tell me the reason why it's force push every time? what's the issues caused before? Thanks.

**Comment by NoahDragon** [comment]
Close this issue as it is similar to #33 .
