### ISSUE TITLE
if branch has ':' will go wrong

### ISSUE THREAD

**Issue by netcan** [hexojs/hexo-deployer-git#40]
my blog has a branch named 'master:1', when I wrote it follow in config.yaml:
```
deploy:
type: git
repo: https://git.sinacloud.com/netcanblog
branch: master:1
```
and I `hexo -d` will go wrong:
```
error: src refspec HEAD:master does not match any.
error: failed to push some refs to 'https://git.sinacloud.com/netcanblog'
```

I think it should be a conflict because it has ':'

**Comment by ottobonn** [comment]
In YAML, the colon is a reserved character. You need to put the branch name in quotes, like this:

    branch: "master:1"
