### ISSUE TITLE
使用hexo -d 没有反应是怎么回事？

### ISSUE THREAD

**Issue by daaoling** [hexojs/hexo-deployer-git#41]
使用hexo -d 没有反应是怎么回事？

zjydeMacBook-Pro:Blog zjy$ hexo d
zjydeMacBook-Pro:Blog zjy$ ls -a
.		.npmignore	node_modules	scaffolds
..		_config.yml	package.json	source
.gitignore	db.json		public		themes
zjydeMacBook-Pro:Blog zjy$ 

.deploy_git 这个目录也没有生成？

**Comment by Xuanwo** [comment]
贴配置文件。

**Comment by daaoling** [comment]
嗯，我犯二了， 空格没加，谢谢回复
