### ISSUE TITLE
deploy之后仓库里的历史文件都被删除

### ISSUE THREAD

**Issue by Shineee** [hexojs/hexo-deployer-git#42]
执行deploy命令之后，原有未更新的旧版本文件都被删除了（比如readme.md文件）
每次更新，我并没有更新readme,但是我github仓库里的readme被删除了
可以保留旧版本文件么？

**Comment by NoahDragon** [comment]
如果希望保留文件，请将文件放到Source文件夹下，然后再deploy.

**Comment by Jiiiiiin** [comment]
@NoahDragon 放到souce目录下之后，在deploy就悲剧了：
![](https://ws2.sinaimg.cn/large/006tKfTcly1fnrrhyx5ycj31hj19ejxh.jpg)
请教怎么解决？
