### ISSUE TITLE
We need .nojekyll file

### ISSUE THREAD

**Issue by soopdop** [hexojs/hexo-deployer-git#51]
Hi. 
Some directories don't appear on the web because of Jekyll.
I found out a solution from the internet: `.nojekyll` file has to be added to the root directory after deployment. Currently, I add that file manually every time after deployment. 
Could you add it to the deploying process? 
thanks.

**Comment by NoahDragon** [comment]
you can add .nojekyll to the source folder, it will be deployed.

**Comment by soopdop** [comment]
@NoahDragon Thank you for your answer!
I think source folder that you said is `.deploy_git`, isn't it?
If I add `.nojekyll` in the `.deploy_git`, It works well.
But If what you mean is just `source` folder, I also have to add below to _config.yml
```
include: 
    - .nojekyll
```
And then, I can see `.nojekyll` file in the `public` directory, but it doesn't copy to `.deploy_git` after deployment.

What did I do wrong?

**Comment by NoahDragon** [comment]
I mean just `source` folder. I will try to reproduce the scenario and take a look why this happens.

**Comment by soopdop** [comment]
@NoahDragon Thank you.
In fact, There was no problem without `.nojekyll` file before a few days. During last a few days, GitHub page shows 404 error for files in some subdirectories such as `vendor`. 

I don't exactly know why, but I guess it is caused by updated Jekyll. (it was updated on Nov. 3. https://github.com/blog/2277-what-s-new-in-github-pages-with-jekyll-3-3)

Why do you think 'vendor' directory is missing?

**Comment by NoahDragon** [comment]
You are right. Jekyll now ignore node-modules and vendor folder as default in order to speed up build time.

Thanks for your link, I finally understand why the following issue happens:
https://github.com/iissnan/hexo-theme-next/issues/1214

**Comment by soopdop** [comment]
@NoahDragon Yeah! I skippingly read that change log. I also found a reason why vendor folder is missing. 
Can I ask you a solution? document on your link is in Chinese, so I can't understand it. And if It's not an issue of `hexo-deployer-git`, I'll close this.

**Comment by NoahDragon** [comment]
It is an issue for git deployer. It should deploy every thing under the public folder. I have created a PR for the fix.

https://github.com/hexojs/hexo-deployer-git/pull/52

**Comment by soopdop** [comment]
Thank you very much!

**Comment by NoahDragon** [comment]
No problem. I will close this issue when the PR merged.

**Comment by NoahDragon** [comment]
#53 has more generic solution which adds a configurable setting.
