### ISSUE TITLE
Does not deploy .htaccess file

### ISSUE THREAD

**Issue by davidwesst** [hexojs/hexo-deployer-git#56]
I have created a generator that generates an .htaccess file in the public directory as expected when I execute the `hexo generate` command.

Unfortunately, I cannot seem to get the git deployer to generate this file in the _.deploy_git_ directory. I have tried setting `ignore_hidden: false` which did not work, nor did specifically setting the _public_ directory to ignore_hidden to false.

This pattern has worked for me in the past, although with files that do not start with a .

My generator is as follows:

```javascript
var fs = require('hexo-fs');
var path = require('path');

hexo.extend.generator.register('htaccess', function(locals) {
    return {
        path: '.htaccess',
        data: function() {
            return fs.createReadStream(path.join(__dirname, '..','.htaccess'));
        }
    }
});
```

**Comment by NoahDragon** [comment]
The hidden files are ignored before last commit. The latest changes are not included in the npm. You could modify the package.json file under your blog root directory from:
``` yml
"hexo-deployer-git": "^0.2.0"
```
to
``` yml
"hexo-deployer-git": "hexojs/hexo-deployer-git"
```

Then reinstall to retrive the latest git deployer.

**Comment by davidwesst** [comment]
Worked like a charm! Thank you. 

@NoahDragon Any idea when/if the new version will be posted to the npm?
