### ISSUE TITLE
Config not works

### ISSUE THREAD

**Issue by ChanterelleFan** [hexojs/hexo-deployer-git#59]
Hello, I use hexo-deployer-git to send blogs to my VPS.  Although my SSH config set port, hexo still use port 22 to connect my vps. Here is my config file:

Host 104.224.164.243
HostName 104.224.164.243
Port 28806
User git
IdentityFile ~/.ssh/id_rsa

When I use "ssh -t git@104.224.164.243" via Terminal, the config file worked. I use macOS Sierra.
Any way to fix this problem? Waiting for your relpy. 
Thank you .

**Comment by NoahDragon** [comment]
Could you please paste your git deployer configuration.

**Comment by ChanterelleFan** [comment]
**Of course.**
**Here is my git deployer configuration:**

deploy:
      type: git
      repo: git@104.224.164.243:/hexo.git
      branch: master

**This is the result  when I use terminal**

ssh -vvt git@104.224.164.243
OpenSSH_7.3p1, LibreSSL 2.4.1
debug1: Reading configuration data /Users/fanjianzeng/.ssh/config
debug1: /Users/fanjianzeng/.ssh/config line 1: Applying options for 104.224.164.243
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 20: Applying options for *
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug2: resolving "104.224.164.243" port 28806

**And this is Hexo-git-deployer shows when I deploy:**

01:13:05.246 FATAL ssh: connect to host 104.224.164.243 port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**I am so confused.**

**Comment by ChanterelleFan** [comment]
Hi, I have fixed this problem.
My SSHKEY saves at /myname/.ssh
But Hexo read SSHKEY from /var/root/.ssh
So I copy all the files to /var/root/.shh and the problem has been fixed.

**Comment by NoahDragon** [comment]
@ChanterelleFan Glad it been fixed.
