### ISSUE TITLE
`extends_dir ` doesn't worked for me

### ISSUE THREAD

**Issue by loatheb** [hexojs/hexo-deployer-git#61]
`'hexo-deployer-git': "^0.2.0"` on [https://www.npmjs.com/package/hexo-deployer-git](https://www.npmjs.com/package/hexo-deployer-git) doesn't  has `"extends_dir"` in it config.

But in this repo, it has been merged([#39](https://github.com/hexojs/hexo-deployer-git/commit/b4ec75713096f3417e19eb34e06997249be41435)) at about six months ago.

I just want to ask when the version `"0.3.0"` with `extends_dir` is released?

**Comment by NoahDragon** [comment]
@tommy351 has the permission to update the npm package.

Currently, you could change the version in `package.jsaon` to the git repo to enable this feature.
`'hexo-deployer-git': "hexojs/hexo-deployer-git"`

**Comment by loatheb** [comment]
@NoahDragon Thank you very much!

```shell
npm i hexo-deployer-git@hexojs/hexo-deployer-git -S 
```
worked for me well.
