### ISSUE TITLE
How to git clone the deployed staff?

### ISSUE THREAD

**Issue by jiapei100** [hexojs/hexo-deployer-git#63]
hexo works perfect with github. However, I've got two questions:

I have my website deployed at: [https://github.com/LongerVision/longervision.github.io](https://github.com/LongerVision/longervision.github.io) , which can be viewed at [https://longervision.github.io/ ](https://longervision.github.io/ ). But, when I changed a laptop, how can I git clone the deployed website -- the current contents in [https://github.com/LongerVision/longervision.github.io](https://github.com/LongerVision/longervision.github.io) is NOT **git push**ed, but **hexo deploy**ed, they are different ...

Thank you 
Pei

**Comment by NoahDragon** [comment]
Simply `git clone https://github.com/LongerVision/longervision.github.io` should work.

**Comment by stevenjoezhang** [comment]
Yes, **git push** and **hexo deploy** are actually the same
