### ISSUE TITLE
deploy 无法将内容发布到 github

### ISSUE THREAD

**Issue by noparkinghere** [hexojs/hexo-deployer-git#67]
deploy 每次都会把全部内容 push 到 github 上，而不是仅将 public 推送。

**Comment by NoahDragon** [comment]
是否在配置文件中branch没有设置正确？

**Comment by noparkinghere** [comment]
还是比较奇怪的，两台电脑差不多的配置步骤：
- sudo npm install hexo-cli -g
- npm install hexo-deployer-git --save
- ~/_config.yml 配置一样，应该是正确的。
差别在于，以前的电脑是可以正确执行的，配置完成后，上传到  github 的，家里的电脑是直接从 github 拉取下来的，然后再安装的 hexo 的，却会将所有内容都上传到 github page。

**Comment by NoahDragon** [comment]
是以下两个Repo么？
![image](https://cloud.githubusercontent.com/assets/5704064/24709341/91a36440-19e7-11e7-8c0b-e445a5dfb0c5.png)

我看已经修复。

**Comment by noparkinghere** [comment]
是的，是这两个库，下面哪个 github page 是我用原来电脑重新 deploy 的。问题出在哪儿，还没能排查出来。

**Comment by Fantasy9527** [comment]
我的mac可以正常使用，我的windows发布的时候跟题主的情况一样，不知道怎么回事？有没有解决？

**Comment by noparkinghere** [comment]
@Fantasy9527 没能发现问题出在哪儿，可能我对 hexo github 本身缺乏一定的理解，我后来上传都用的原来的电脑，没再用那台电脑重新配置了。

**Comment by Fantasy9527** [comment]
会不会是fsevent 不兼容Windows系统的原因?

**Comment by loatheb** [comment]
另一个仓库是直接从 github clone 下来然后用插件 deploy 的么？

如果是，建议删掉 .git .deploy_git `hexo clean` 然后试一下

**Comment by Fantasy9527** [comment]
@loatheb  
我删除了 .deploy_git,重新发布就正常了.
谢谢你

**Comment by noparkinghere** [comment]
@loatheb 先谢谢，等回头有空试下，上次传出问题，弄得我把整个库删了重建~

**Comment by stevenjoezhang** [comment]
这个 Issue 先关了，有其他问题欢迎讨论～
