### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by bigdots** [hexojs/hexo-deployer-git#72]
当我使用hexo d部署时，sitemap.xml／atom.xml等xml格式文件会被忽略，上传不到仓库

**Comment by NoahDragon** [comment]
我的網站沒有此類問題。能否將有問題代碼放在一個Repo中呢？

**Comment by bigdots** [comment]
您好，我已经把代码上传了（https://github.com/bigdots/hexo-demo），麻烦您看下

**Comment by bigdots** [comment]
发现这样上传，xml文件，也是没传上来

**Comment by bigdots** [comment]
sorry，我好像在全局的.gitignore设置了忽略xml文件
