### ISSUE TITLE
How to deploy to docs folder of a project pages site

### ISSUE THREAD

**Issue by garywu** [hexojs/hexo-deployer-git#76]
It's not clear hexo-deployer-git can support deploy to a /docs folder. Github pages allow depolyment to a /docs folder on a master branch. I'd like to know how to configure hexo-deployer-git for this case.

https://help.github.com/articles/user-organization-and-project-pages/

Type of github site: Project Pages site owned by an organization
github path: orgname.github.io/projectname
page site: master, gh-pages, or a /docs folder on master

**Comment by NoahDragon** [comment]
Hexo-deployer-git deploys on branches, I don't think it could deploy to a certain folder.

**Comment by garywu** [comment]
Thanks for the quick reply. I can look into a PR any pointers?

**Comment by stevenjoezhang** [comment]
For GitHub pages:
In `_config.yml`:
1.
```
url: https://orgname.github.io/docs
root: /docs/
```
Then create a repository called `docs`, and deploy the site to its `master` branch.

**Comment by schtonn** [comment]
Like this?
![image](https://user-images.githubusercontent.com/60652675/82281174-47c53380-99c3-11ea-9545-24f1555948e4.png)
![image](https://user-images.githubusercontent.com/60652675/82281198-54e22280-99c3-11ea-84da-0ad9a6be4d49.png)
But it turns out 404:/

**Comment by stevenjoezhang** [comment]
@schtonn You can find the settings about GitHub pages in the settings page of the `blog` repository, and then select the master branch as `source`.

**Comment by schtonn** [comment]
Thanks, now it's working
