### ISSUE TITLE
Can SSL certificates with a passphrase be used?

### ISSUE THREAD

**Issue by jeffheaton** [hexojs/hexo-deployer-git#77]
I can deploy to gihub just fine if I use HTTPS and provide my user id and password.  Likewise, I can deploy just fine if I use an SSL cert that has no passphrase.  But if I try to deploy with a passphrase I get:

Error: Permission denied (publickey).
fatal: Could not read from remote repository.

How do I provide my passkey to hexo-deployer-git?

**Comment by NoahDragon** [comment]
Please correct me if I'm wrong because I never used the passphrase for github repos.

Based on the instruction https://help.github.com/articles/working-with-ssh-key-passphrases/ , I think just run `ssh-add` should work.

**Comment by jeffheaton** [comment]
I still could not get it to work.  I ended up just writing a deploy shell script, so this is no longer an issue.  Also, FYI, another issue that I noted with hexo-deployer-git is that it always reuploads my entire site, even if I change one file.  What I do in my script is sync with the github site and then render over top.

**Comment by NoahDragon** [comment]
@jeffheaton thanks for sharing the solution. The uploading entire site is intentional, as when git conflict occurs, it is hard to resolve the confliction automatically.
