### ISSUE TITLE
deploy 到 github 时报错

### ISSUE THREAD

**Issue by yiyizym** [hexojs/hexo-deployer-git#8]
操作系统 mac ox 10.10.4
nodejs 版本 v0.12.7
hexo-deployer-git 版本 0.0.4

提示信息：

➜  blog  hexo deploy     
[info] Start deploying: git
[error] TypeError: Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at Object.module.exports [as git] (/Users/zhu/Documents/blog/node_modules/hexo-deployer-git/lib/deployer.js:18:26)
    at /usr/local/lib/node_modules/hexo/lib/plugins/console/deploy.js:76:22
    at iterate (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:165:9)
    at /usr/local/lib/node_modules/hexo/lib/plugins/console/deploy.js:66:11
    at /usr/local/lib/node_modules/hexo/lib/plugins/console/deploy.js:32:27
    at FSReqWrap.cb [as oncomplete] (evalmachine.<anonymous>:226:19)

**Comment by Xuanwo** [comment]
贴一下你的deploy设置~

**Comment by yiyizym** [comment]
\# Deployment
\## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/yiyizym/blog
  branch: gh-pages

**Comment by Xuanwo** [comment]
`repo`改成`https://github.com/yiyizym/blog.git`

**Comment by yiyizym** [comment]
改过来之后，还是报这个错。

\# Deployment
\## Docs: http://hexo.io/docs/deployment.html
 deploy:
 type: git
 repo: https://github.com/yiyizym/blog.git 
 branch: gh-pages

➜  blog  hexo deploy    
[info] Start deploying: git
[error] TypeError: Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at Object.module.exports [as git] (/Users/zhu/Documents/blog/node_modules/hexo-deployer-git/lib/deployer.js:18:26)
    at /usr/local/lib/node_modules/hexo/lib/plugins/console/deploy.js:76:22
    at iterate (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:165:9)
    at /usr/local/lib/node_modules/hexo/lib/plugins/console/deploy.js:66:11
    at /usr/local/lib/node_modules/hexo/lib/plugins/console/deploy.js:32:27
    at FSReqWrap.cb [as oncomplete] (evalmachine.<anonymous>:226:19)

**Comment by Xuanwo** [comment]
```
deploy:
type: git
repo: https://github.com/yiyizym/blog.git 
branch: gh-pages
```
改成
```
deploy:
  type: git
  repo: https://github.com/yiyizym/blog.git 
  branch: gh-pages
```

试试看

**Comment by yiyizym** [comment]
文件里是有缩进的，贴上来被省略掉了。
```
  # Deployment
  ## Docs: http://hexo.io/docs/deployment.html
  deploy:
    type: git
    repo: https://github.com/yiyizym/blog.git
    branch: gh-pages
```

对 nodejs 不熟悉，有办法看看 deploy.js 第76行的 this.base_dir 是不是 undefined 吗？

**Comment by Xuanwo** [comment]
你把`.deployer_git`文件夹删掉再试试

**Comment by yiyizym** [comment]
在整个项目里没有找到这个文件夹啊。

**Comment by Xuanwo** [comment]
sorry

应该是`.deploy_git`

**Comment by yiyizym** [comment]
也没有。

**Comment by Xuanwo** [comment]
你的Hexo版本是？

**Comment by yiyizym** [comment]
2.8.3

```
➜  blog  hexo -v
hexo: 2.8.3
os: Darwin 14.4.0 darwin x64
http_parser: 2.3
node: 0.12.7
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1p
```

**Comment by Xuanwo** [comment]
请升级到3.1.1或者使用hexo-deployer-git@0.0.1

**Comment by yiyizym** [comment]
@Xuanwo  谢谢！升级到3.1.1 问题解决了。

昨晚试过 使用hexo-deployer-git@0.0.2 ，就差一点。。。
