### ISSUE TITLE
删除github上的库重建以后，public和source等文件夹无法同步到github上

### ISSUE THREAD

**Issue by Pudgedd** [hexojs/hexo-deployer-git#85]
删除github上的库重建以后，public和source等文件夹无法同步到github上，目前github上文件结构不完整，访问出现404.
这是我的地址，求助！
https://github.com/Pudgedd/Pudgedd.github.io

**Comment by NoahDragon** [comment]
似乎已经修复了~

**Comment by cutelittleturtle** [comment]
这个插件默认只上传public/下的文件。如果你想上传其他文件夹，在_config里面设置ignore

**Comment by Pudgedd** [comment]
@NoahDragon 新手一枚，慢慢折腾弄好了，谢谢回复~
