### ISSUE TITLE
"git+git": name can only contain URL-friendly characters

### ISSUE THREAD

**Issue by codefine** [hexojs/hexo-deployer-git#86]
When I use `$ npm install git+git@github.com:hexojs/hexo-deployer-git.git --save` to install the lasted feature of hexo-deployer, it report the message like this:
_Invalid package name "git+git": name can only contain URL-friendly characters_

Help me solve this problem plz.

**Comment by NoahDragon** [comment]
Have you tried the `npm i hexojs/hexo-deployer-git --save`?

**Comment by codefine** [comment]
Sorry, I made some mistakes. This issue can be close.
I want to deploy with this:
``` bash
deploy:
  - type: git
    repo: git@github.com:<username>/<username>.github.io.git
    branch: master
  - type: git
    repo: git@github.com:<username>/<username>.github.io.git
    branch: src
    extend_dirs: /
    ignore_hidden: false
    ignore_pattern:
        public: .
```
It reported some errors so that I thought the config above must be ran with the lasted released.
But now it works~
Thanks alot. ^_^

**Comment by loatheb** [comment]
@NoahDragon @CodeFalling 

at npm@5 it seems doesn't support `npm install git+git@github.com:hexojs/hexo-deployer-git.git` any more. So update another command for npm@5.
