### ISSUE TITLE
When Deploying, Resets My Custom Domain

### ISSUE THREAD

**Issue by ToddAT** [hexojs/hexo-deployer-git#87]
When using the deploy script, I've noticed that my custom domain configuration gets overwritten/reset. Is there something I need to set in the config? Otherwise, any idea how to fix this?

**Comment by loatheb** [comment]
@ToddAT make your CNAME file under source folder.It will be copied to root when build result.

**Comment by green-coder** [comment]
That's worth being added to the README.md

**Comment by noodlemaster** [comment]
Can someone plz help me...
https://github.com/hexojs/hexo/issues/4205

**Comment by erikh** [comment]
Agree, please add this to the README as I was super confused. Thanks.

**Comment by dimaslanjaka** [comment]
just write below codes to generate in root hexo site project. Lets assume `<hexodir>/generate.js`
```js
const hexo = require("hexo");
const fs = require("fs");
const path = require("path");
hexo
  .init()
  .then(hexo.load)
  .then(() => hexo.call("generate"))
  .then(() => {
    fs.writeFileSync(
      path.join(__dirname, "public/CNAME"),
      "www.example.net"
    );
  })
  .catch(hexo.exit);
```

usage: `node generate.js`

it should be generate the site and creating CNAME after generated

## OR 

creating CNAME inside source directory
