### ISSUE TITLE
想部署和备份源码命令分开

### ISSUE THREAD

**Issue by wulinfo** [hexojs/hexo-deployer-git#88]
deploy:
  - type: git
    repo: git@github.com:xxx/hexo.git
    branch: master
  - type: git
    repo: git@github.com:xxx/hexo.git
    branch: src
    extend_dirs: /
    ignore_hidden: false
    ignore_pattern:
        public: .

每次部署连带备份源码花的时间有些长，所以需求类似
hexo g -d这类命令，hexo d -b（bak）这样可行

**Comment by NoahDragon** [comment]
我的做法是讲源码repo和travis-ci相链接，当更新源码后，travis-ci会自动讲生成的文件部署到网站。

**Comment by tyrionyu** [comment]
@NoahDragon 没看懂。

**Comment by tyrionyu** [comment]
@wulinfo 分别备份github不同的repositories可以吗？

**Comment by NoahDragon** [comment]
@tyrionyu 可以的，可以将source和site放不同的repo中。

**Comment by tyrionyu** [comment]
@NoahDragon 谢谢！分两个repo我做好了，我在github上建了两个repo，一个是soure。一个是部署生成的。现在我还想把主题也同步，我自己改了主题想同步上去。原作者的主题有更新我也想把他给pull下来。不知道要怎么弄。

**Comment by zhoushirong** [comment]
没必要备份源码，开发（写博客）的时候用develop或者其他分支；
deploy的时候指定master分支；

这样两个分支互不相干，master分支就专门用作发布。源码保存在开发分支。
