### ISSUE TITLE
Replace swig with swig-templates

### ISSUE THREAD

**Issue by h404bi** [hexojs/hexo-deployer-git#99]
Synchronize the changes in [Hexo 3.5.0](https://github.com/hexojs/hexo/pull/2949/files)

https://github.com/hexojs/hexo-deployer-git/blob/master/package.json#L43

**Comment by JLHwung** [comment]
Good catch! Could you draft a PR on that?

**Comment by h404bi** [comment]
Got it, please give it a review.
